5 module
js-tasks-ru/jsbasic-20221114_yuriy97 pull request #6
Opened 2022-12-12 15:48 UTC by yaandreev

2022-12-12 15:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-14 09:21 UTC, SinimaWath requested changes

2022-12-14 09:21 UTC, SinimaWath commented on 5-module/1-task/index.js
> +    elem.setAttribute("hidden", "true");
`elem.hidden = true`

2022-12-14 09:21 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    text.hasAttribute("hidden") ? text.removeAttribute("hidden") : text.setAttribute("hidden", "true");
Можно заменить на: `text.hidden = !text.hidden`, так как это стандартный атрибут

2022-12-14 09:21 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  }
2 эти функции почти полностью одинаковые. Кроме 20 и 13 строчки, попробуй вынести общий функционал в функцию

2022-12-14 13:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-15 11:39 UTC, SinimaWath approved these changes

2022-12-15 11:40 UTC, merged